# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(974, 860)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_Second = QtWidgets.QLabel(self.centralwidget)
        self.label_Second.setGeometry(QtCore.QRect(610, 30, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(14)
        self.label_Second.setFont(font)
        self.label_Second.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_Second.setObjectName("label_Second")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(580, 30, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_17.setObjectName("label_17")
        self.label_Minute = QtWidgets.QLabel(self.centralwidget)
        self.label_Minute.setGeometry(QtCore.QRect(540, 30, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(14)
        self.label_Minute.setFont(font)
        self.label_Minute.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_Minute.setObjectName("label_Minute")
        self.label_Hour = QtWidgets.QLabel(self.centralwidget)
        self.label_Hour.setGeometry(QtCore.QRect(470, 30, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(14)
        self.label_Hour.setFont(font)
        self.label_Hour.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_Hour.setObjectName("label_Hour")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(510, 30, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(14)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_18.setObjectName("label_18")
        self.label_Hour_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_Hour_2.setGeometry(QtCore.QRect(320, 30, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(14)
        self.label_Hour_2.setFont(font)
        self.label_Hour_2.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_Hour_2.setObjectName("label_Hour_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 450, 911, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.pushButton_SaveHistory = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_SaveHistory.setGeometry(QtCore.QRect(20, 40, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_SaveHistory.setFont(font)
        self.pushButton_SaveHistory.setStyleSheet("background-color: rgb(170, 85, 0);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_SaveHistory.setObjectName("pushButton_SaveHistory")
        self.pushButton_SaveForecast = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_SaveForecast.setGeometry(QtCore.QRect(300, 40, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_SaveForecast.setFont(font)
        self.pushButton_SaveForecast.setStyleSheet("background-color: rgb(85, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_SaveForecast.setObjectName("pushButton_SaveForecast")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 190, 911, 241))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget.setGeometry(QtCore.QRect(20, 80, 871, 141))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(24)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(23, item)
        self.pushButton_Update = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_Update.setGeometry(QtCore.QRect(20, 40, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Update.setFont(font)
        self.pushButton_Update.setStyleSheet("background-color: rgb(0, 0, 159);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_Update.setObjectName("pushButton_Update")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(40, 69, 901, 101))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.lineEdit_Longitude = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_Longitude.setEnabled(True)
        self.lineEdit_Longitude.setGeometry(QtCore.QRect(510, 60, 201, 20))
        self.lineEdit_Longitude.setReadOnly(True)
        self.lineEdit_Longitude.setObjectName("lineEdit_Longitude")
        self.lineEdit_Latitude = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_Latitude.setEnabled(True)
        self.lineEdit_Latitude.setGeometry(QtCore.QRect(290, 60, 201, 20))
        self.lineEdit_Latitude.setReadOnly(True)
        self.lineEdit_Latitude.setObjectName("lineEdit_Latitude")
        self.comboBox_City = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_City.setGeometry(QtCore.QRect(170, 60, 101, 20))
        self.comboBox_City.setObjectName("comboBox_City")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(200, 30, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(570, 30, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(360, 30, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 570, 911, 211))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.listWidget = QtWidgets.QListWidget(self.groupBox_4)
        self.listWidget.setGeometry(QtCore.QRect(20, 30, 631, 161))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.pushButton_Clear = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_Clear.setGeometry(QtCore.QRect(660, 160, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Clear.setFont(font)
        self.pushButton_Clear.setStyleSheet("background-color: rgb(83, 83, 83);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_Clear.setObjectName("pushButton_Clear")
        self.pushButton_Export = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_Export.setGeometry(QtCore.QRect(780, 160, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Export.setFont(font)
        self.pushButton_Export.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_Export.setObjectName("pushButton_Export")
        self.label_Day = QtWidgets.QLabel(self.centralwidget)
        self.label_Day.setGeometry(QtCore.QRect(140, 30, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(14)
        self.label_Day.setFont(font)
        self.label_Day.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_Day.setObjectName("label_Day")
        self.label_Month = QtWidgets.QLabel(self.centralwidget)
        self.label_Month.setGeometry(QtCore.QRect(100, 30, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(14)
        self.label_Month.setFont(font)
        self.label_Month.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_Month.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_Month.setObjectName("label_Month")
        self.label_Year = QtWidgets.QLabel(self.centralwidget)
        self.label_Year.setGeometry(QtCore.QRect(40, 30, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(14)
        self.label_Year.setFont(font)
        self.label_Year.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_Year.setObjectName("label_Year")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(130, 30, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(14)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(90, 30, 16, 31))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(14)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_20.setObjectName("label_20")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 974, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Second.setText(_translate("MainWindow", "S"))
        self.label_17.setText(_translate("MainWindow", "："))
        self.label_Minute.setText(_translate("MainWindow", "M"))
        self.label_Hour.setText(_translate("MainWindow", "H"))
        self.label_18.setText(_translate("MainWindow", "："))
        self.label_Hour_2.setText(_translate("MainWindow", "Current time"))
        self.groupBox.setTitle(_translate("MainWindow", "Manually save files"))
        self.pushButton_SaveHistory.setText(_translate("MainWindow", "Save Yesterday\'s report"))
        self.pushButton_SaveForecast.setText(_translate("MainWindow", "Save Tomorrow\'s forecast"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Today\'s weather"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Temperature"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Humidity"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "00:00"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "01:00"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "02:00"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "03:00"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "04:00"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "05:00"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "06:00"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "07:00"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "08:00"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "09:00"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "10:00"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "11:00"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "12:00"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "13:00"))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "14:00"))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "15:00"))
        item = self.tableWidget.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "16:00"))
        item = self.tableWidget.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "17:00"))
        item = self.tableWidget.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "18:00"))
        item = self.tableWidget.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "19:00"))
        item = self.tableWidget.horizontalHeaderItem(20)
        item.setText(_translate("MainWindow", "20:00"))
        item = self.tableWidget.horizontalHeaderItem(21)
        item.setText(_translate("MainWindow", "21:00"))
        item = self.tableWidget.horizontalHeaderItem(22)
        item.setText(_translate("MainWindow", "22:00"))
        item = self.tableWidget.horizontalHeaderItem(23)
        item.setText(_translate("MainWindow", "23:00"))
        self.pushButton_Update.setText(_translate("MainWindow", "UPDATE"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Setting"))
        self.label_9.setText(_translate("MainWindow", "City"))
        self.label_11.setText(_translate("MainWindow", "Longitude"))
        self.label_10.setText(_translate("MainWindow", "Latitude"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Operation log"))
        self.pushButton_Clear.setText(_translate("MainWindow", "CLEAR"))
        self.pushButton_Export.setText(_translate("MainWindow", "EXPORT"))
        self.label_Day.setText(_translate("MainWindow", "D"))
        self.label_Month.setText(_translate("MainWindow", "M"))
        self.label_Year.setText(_translate("MainWindow", "Y"))
        self.label_19.setText(_translate("MainWindow", "/"))
        self.label_20.setText(_translate("MainWindow", "/"))

